### ISSUE TITLE
QGB orchestrator checkout routine

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/orchestrator-relayer#1]
We could implement in the orchestrator an extra go routine that checks periodically if all the attestations that need to be signed were signed. And queue the missed ones.
_Originally posted by @SweeXordious in https://github.com/celestiaorg/celestia-app/pull/512#discussion_r912296319_

**Comment by SweeXordious** [comment]
I don't think this makes sense anymore because when the orchestrator starts, it enqueues all the nonces that need to be signed. And if one nonce fails, it is retried a few times then the orchestrator goes down...
Thus, there is no case where a nonce is missed and needs to be re-enqueued using a special routine
